#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/root/tanniere-monitoring-1/client"
ENV_FILE="$ROOT_DIR/.env"
CONF_FILE="/etc/mosquitto/conf.d/90-victron-bridge.conf"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE"
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

: "${BRIDGE_REMOTE_HOST:=}"
: "${BRIDGE_REMOTE_PORT:=8883}"
: "${BRIDGE_REMOTE_USERNAME:=}"
: "${BRIDGE_REMOTE_PASSWORD:=}"
: "${BRIDGE_TOPIC:=victron/vedirect/#}"

if [[ -z "$BRIDGE_REMOTE_HOST" ]]; then
  echo "BRIDGE_REMOTE_HOST is empty in .env"
  echo "Set BRIDGE_REMOTE_HOST and rerun this script."
  exit 1
fi

apt-get update
apt-get install -y mosquitto mosquitto-clients ca-certificates

cat > "$CONF_FILE" <<EOF
# Generated by configure-mosquitto-bridge.sh
# Read-only filesystem mode: best-effort RAM-only buffering.

listener 1883 127.0.0.1
allow_anonymous true

# No disk persistence on read-only hosts.
persistence false

connection victron-cloud
address ${BRIDGE_REMOTE_HOST}:${BRIDGE_REMOTE_PORT}
topic ${BRIDGE_TOPIC} out 1

remote_username ${BRIDGE_REMOTE_USERNAME}
remote_password ${BRIDGE_REMOTE_PASSWORD}

bridge_protocol_version mqttv311
bridge_cafile /etc/ssl/certs/ca-certificates.crt
bridge_tls_version tlsv1.2
try_private false
cleansession false
start_type automatic
notifications false

# RAM queue while WAN is down; lost on reboot.
queue_qos0_messages true
max_queued_messages 5000
restart_timeout 5 30
EOF

systemctl enable --now mosquitto
systemctl restart mosquitto

echo "Configured local volatile Mosquitto bridge: $CONF_FILE"
echo "Best-effort only: queued messages are lost on reboot."